"""fixesd room_name field of record

Revision ID: 33fa9ec39057
Revises: ffb2b4bab538
Create Date: 2024-04-22 20:37:46.562388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33fa9ec39057'
down_revision: Union[str, None] = 'ffb2b4bab538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('room_name', sa.Text(), nullable=True))
    op.drop_column('records', 'nicknames')
    op.add_column('records_history', sa.Column('room_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records_history', 'room_name')
    op.add_column('records', sa.Column('nicknames', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('records', 'room_name')
    # ### end Alembic commands ###
