"""empty message

Revision ID: 5a21c9f9ae16
Revises: 182fb1ab0336
Create Date: 2024-03-23 14:09:09.958360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a21c9f9ae16'
down_revision: Union[str, None] = '182fb1ab0336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nicknames', sa.Column('history_record_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'nicknames', 'records_history', ['history_record_id'], ['id'])
    op.drop_column('records_history', 'nicknames')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records_history', sa.Column('nicknames', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'nicknames', type_='foreignkey')
    op.drop_column('nicknames', 'history_record_id')
    # ### end Alembic commands ###
