"""empty message

Revision ID: 8848729b602b
Revises: 231169fa53d1
Create Date: 2024-03-23 21:10:26.400176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8848729b602b'
down_revision: Union[str, None] = '231169fa53d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('found_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'records', 'founds', ['found_id'], ['id'])
    op.add_column('records_history', sa.Column('found_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'records_history', 'founds', ['found_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'records_history', type_='foreignkey')
    op.drop_column('records_history', 'found_id')
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.drop_column('records', 'found_id')
    # ### end Alembic commands ###
