"""empty message

Revision ID: ad69f6f32c52
Revises: f539b7c8715d
Create Date: 2024-03-23 14:26:06.594652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad69f6f32c52'
down_revision: Union[str, None] = 'f539b7c8715d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records_history', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('records_history_created_by_id_fkey', 'records_history', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('records_history_created_by_id_fkey', 'records_history', 'users', ['created_by_id'], ['id'])
    op.alter_column('records_history', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
