"""empty message

Revision ID: f539b7c8715d
Revises: b4e275025770
Create Date: 2024-03-23 14:25:13.553565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f539b7c8715d'
down_revision: Union[str, None] = 'b4e275025770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records_history', sa.Column('current_version_id', sa.Integer(), nullable=False))
    op.drop_constraint('records_history_current_version_fkey', 'records_history', type_='foreignkey')
    op.create_foreign_key(None, 'records_history', 'records', ['current_version_id'], ['id'])
    op.drop_column('records_history', 'current_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records_history', sa.Column('current_version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'records_history', type_='foreignkey')
    op.create_foreign_key('records_history_current_version_fkey', 'records_history', 'records', ['current_version'], ['id'])
    op.drop_column('records_history', 'current_version_id')
    # ### end Alembic commands ###
