"""empty message

Revision ID: f5c37537019e
Revises: ad69f6f32c52
Create Date: 2024-03-23 14:27:16.185100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c37537019e'
down_revision: Union[str, None] = 'ad69f6f32c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records_history', 'created_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records_history', sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
