"""changed nicknames to room_name

Revision ID: ffb2b4bab538
Revises: db2a10e5281e
Create Date: 2024-04-22 20:19:32.163378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffb2b4bab538'
down_revision: Union[str, None] = 'db2a10e5281e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nicknames')
    op.add_column('records', sa.Column('nicknames', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'nicknames')
    op.create_table('nicknames',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('nickname', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('history_record_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['history_record_id'], ['records_history.id'], name='nicknames_history_record_id_fkey'),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], name='nicknames_record_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='nicknames_pkey')
    )
    # ### end Alembic commands ###
