"""empty message

Revision ID: 48760709e1f9
Revises: abca7cd51987
Create Date: 2024-03-14 19:25:19.559753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48760709e1f9'
down_revision: Union[str, None] = 'abca7cd51987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('founds', 'discord',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('users', 'by_fathers_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('users', 'contact_fields',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('users', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=320),
               existing_nullable=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('users', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'contact_fields',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('users', 'by_fathers_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'username')
    op.alter_column('founds', 'discord',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
