"""empty message

Revision ID: 560f29f40ba2
Revises: 2dd6d28ce079
Create Date: 2024-03-16 14:53:10.397140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560f29f40ba2'
down_revision: Union[str, None] = '2dd6d28ce079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nicknames', sa.JSON(none_as_null=True), nullable=True))
    op.add_column('users', sa.Column('gipsy_team', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gipsy_team')
    op.drop_column('users', 'nicknames')
    # ### end Alembic commands ###
